import { useLocation } from "react-router-dom";
import "./Landing.css"
import Button from "../../components/Button/Button";
import { useContext } from "react";
import CartItemsContext, { cartItem } from "../CartItemsContext/CartItemsContext";
import useFetch from "../../Hooks/fetch";

const Landing = () => {

    const { state } = useLocation();

    const { courses } = state || {};

    const { fetch } = useFetch()

    const cartContext = useContext(CartItemsContext);

    const handleAddToCart = (course: cartItem) => {
        if(cartContext) {
            cartContext.setCartItems([...cartContext.cartItems, course])
            fetch('/addtocart', 'POST', {
                cartItems: [...cartContext.cartItems, course]
            })
        }
    }

    return courses && courses.length ?
    <>
        <div className="course-courselist">
            { 
                courses.map((course: cartItem) => {
                    // we are using _id generated by Mongodb during document(row) insertion
                    const isInCart = cartContext && cartContext.cartItems.findIndex(item => item._id === course._id) > -1;
                    return (
                        <div className="course-item" key={`${course.name}+${course.instructorDetails}`}>
                            <img className="course-image" src={course.img} />
                            <p className="course-name">{course.name}</p>
                            <strong className="course-instructor">{course.instructorDetails}</strong>
                            <p className="course-ratings">ratings: {course.rating}</p>
                            <p className="course-price">${course.price}</p>
                            <Button disabled={ !!isInCart } className="course-addtocart" text="Buy now" onClick={() => handleAddToCart(course)}/>
                        </div>
                    )
                })
            }
            </div>
    </> 
    :
    null;
}

export default Landing;